manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cjpeterein
      url-base: https://github.com/cjpeterein
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-split-display-view
      remote: cjpeterein
      revision: 756af75ed65c6a7ce65eb24b668880b85537577b
  self:
    path: config
